### ISSUE TITLE
Cannot construct class definition - just inheritence - intermittent

### ISSUE THREAD

**Issue by mgalloy** [mgalloy/idldoc#48]
I think that there is a problem when IDLDoc tries to construct a class definition for a class that just inherits. For example:

```
pro star_course_vs_time_receiver_request`__`define 
  struct = { star_course_vs_time_receiver_request, $ 
             inherits star_single_receiver_request } 
end
```

Produces the following error:

```
IDLDOC: cannot construct definition for class star_course_vs_time_receiver_request
```

This doesn't seem to happen all of the time, but I can't find a consistent thread to indicate when this problem occurs and when it doesn't.

**Comment by kimyx** [comment]
For what it's worth, we see this error consistently when mgunit tests are parsed via idldoc. The doc output seems ok, but we get this message:

```
00:00:30.585 % Compiled module: CONFIG_UT__DEFINE.
00:00:30.585 % IDLDOC: cannot construct definition for class config_ut
```

These test cases inherit MGutTestCase, which is available on the path.

**Comment by mgalloy** [comment]
They inherit *only* from `MGutTestCase`?

**Comment by kimyx** [comment]
Yes. Here's the complete class definition for the message referenced above.

```
pro config_ut__define
  compile_opt strictarr

  define = { config_ut, inherits MGutTestCase }
end
```
I can strip down the complete file and send it if that would help.

**Comment by mgalloy** [comment]
If you could make a small example that shows the problem and send it to me, that would be great!

-Mike

...from my phone, so likely even briefer than normal

**Comment by mgalloy** [comment]
I got the same issue you are reporting until I made sure `MGutTestCase` was resolved before running IDLdoc. Remember: if you are using the mgunit `.sav` file distribution, then you need to `RESTORE` `mgunit.sav` before running IDLdoc to make `MGutTestCase` available (since it will not automatically be found in `mgunit.sav` since it has a different name).

Please let me know if this resolves your issue.

**Comment by kimyx** [comment]
Yes, I'm glad it was that easy! I assumed this wasn't necessary since the tests find and resolve mgunit when they are run, but of course they aren't being run when the doc is built. For the record, I added this code to the start of our documentation batch job:

```
; must restore mgunit.sav or there will be warnings in the log
  print, 'Restoring mgunit'
  mgunit_path = strsplit(!path,path_sep(/SEARCH_PATH),/extract)
  mgunit_path = mgunit_path + path_sep() + 'mgunit.sav'
  mgunit_file = file_search(mgunit_path)
  if n_elements(mgunit_file) ge 1 then restore, mgunit_file[0] & print, 'Restored mgunit'
```

**Comment by mgalloy** [comment]
Great, I will close this ticket.

By the way, I would do:

    mgunit_file = file_which('mgunit.sav')
    if (n_elements(mgunit_file) gt 0) then restore, mgunit_file[0] & print, 'Restored mgunit'

**Comment by kimyx** [comment]
Thanks Mike. More library routines to become familiar with...
