### ISSUE TITLE
COMMENT_STYLE keyword only changes the extension of the output

### ISSUE THREAD

**Issue by sappjw** [mgalloy/idldoc#86]
When using different `COMMENT_STYLE` keyword settings (e.g., 'plain' or 'rst'), the only thing that changes about the output is the extension of the resulting files.  The content remains HTML.

**Comment by mgalloy** [comment]
I will take a look at this. Are you using the latest release or the GitHub repo?

Also, the options for `COMMENT_STYLE` are "rst", "html", or "latex".

**Comment by sappjw** [comment]
I'm using the repo HEAD.
And I'd like the RST output, but I wanted to try other options based on [these lines](https://github.com/mgalloy/idldoc/blob/master/src/doc_system__define.pro#L1906-L1912).

**Comment by mgalloy** [comment]
Ah, `TEMPLATE_PREFIX` needs to change with `COMMENT_STYLE`. I have added a commit (19a93c8) that automatically sets `TEMPLATE_PREFIX` for "latex" and "docbook" comment styles. There are currently no templates for "rst" and "plain" output; if you play around with this and create some, please make a pull request!

Please let me know if this helps.

**Comment by sappjw** [comment]
I see, thanks for the clarification.

**Comment by mgalloy** [comment]
The two-step process wasn't very user-friendly. Hopefully it will be easier to deal with now.
