### ISSUE TITLE
undefined procedure: 'MGCOARRAYLIST__DEFINE' when running first tutorial example

### ISSUE THREAD

**Issue by vincenzooo** [mgalloy/idldoc#87]
I try to run the first command of the tutorial, I receive this error:
IDLDOC: Attempt to call undefined procedure: 'MGCOARRAYLIST__DEFINE'.

and I cannot locate any procedure with that name.
I believe I followed the instructions, what am I doing wrong?

**Comment by mgalloy** [comment]
You have to pull in the submodules. The `lib` submodule is `mglib` which contains that. Use the `init.sh` script in the root of the repository.

**Comment by vincenzooo** [comment]
Thanks, it worked!
